export const actionTypes = {
  FETCH_BOOKMARKS: 'FETCH_BOOKMARKS',
  FETCH_BOOKMARKS_SUCCESS: 'FETCH_BOOKMARKS_SUCCESS',
  FETCH_BOOKMARKS_ERROR: 'FETCH_BOOKMARKS_ERROR',
  FETCH_COLLECTIONS: 'FETCH_COLLECTIONS',
  FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
  FETCH_COLLECTIONS_ERROR: 'FETCH_COLLECTIONS_ERROR',
  SET_CURRENT_COLLECTION: 'SET_CURRENT_COLLECTION',
  SET_BOOKMARKS_SEARCH: 'SET_BOOKMARKS_SEARCH',
  SIGN_IN: 'SIGN_IN',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_ERROR: 'SIGN_IN_ERROR'
};
