export const actionTypes = {
  FETCH_BOOKMARKS: 'FETCH_BOOKMARKS',
  FETCH_COLLECTIONS: 'FETCH_COLLECTIONS',
  FETCH_BOOKMARKS_SUCCESS: 'FETCH_BOOKMARKS_SUCCESS',
  FETCH_BOOKMARKS_ERROR: 'FETCH_BOOKMARKS_ERROR'
};